Vagrant.configure("2") do |config|
  config.vm.box ="ubuntu/trusty64"

  config.vm.define :"kvm1" do |app|
    app.vm.hostname = "kvm1"
    app.vm.network :private_network, ip: "192.168.100.10"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  config.vm.define :"kvm2" do |app|
    app.vm.hostname = "kvm2"
    app.vm.network :private_network, ip: "192.168.100.20"
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end
end
