Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  # ubuntu-desktop をインストール
  config.vm.provision :shell, :inline => "sudo apt-get update && sudo apt-get install -y ubuntu-desktop"
  # X11 Fowarding を有効にする
  config.ssh.forward_x11 = true

  config.vm.hostname = "ubuntu-xforwarding"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

end
