Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "trusty-bare"

  config.vm.provision "shell", path: "../../apt-upgrade.sh", privileged: true
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.gui = true
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
